version: 2
jobs:
  build-dev:
    docker:
      image: circleci/node:9

    branches:
      only: stage

    steps:
      - run:
        name: Installing dependencies
        commaned: yarn

      - run:
        name: Running tests
        command: yarn test

      - run:
        name: Deploying to Now staging
        command: now
