version: 2
jobs:
  test:
    docker:
      image: circleci/node:9

    steps:
      run:
        name: Installing dependencies
        commaned: yarn

      run:
        name: Running tests
        command: yarn test

  deploy-stage:
    steps:
      run:
        name: Deploying to Now staging
        command: now

workflows:
  test:
    jobs: test

  test_deploy_stage:
    requires: test

    filters:
      branches:
        only: stage

    jobs: deploy-stage
