version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9

    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Running tests
          command: yarn test

  deploy-stage:
    docker:
      - image: circleci/node:9

    steps:
      - checkout
      - run:
          name: Install now
          command: yarn global add now

      - deploy:
          name: Deploying to Now staging
          command: now -t {NOW_TOKEN}

workflows:
  version: 2
  test:
    jobs:
      - test

  test-deploy-stage:
    jobs:
      - deploy-stage:
          requires:
            - test

          filters:
            branches:
              only: stage
